<a href="https://colab.research.google.com/github/koeyhnim/banghak/blob/main/my_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("HelloWorld!")

HelloWorld!


In [2]:
%%time

import torch
from torch import optim
import torch.nn as nn
import torch.nn.functional as F
from torchvision.datasets import CIFAR10
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

cifar10_train = CIFAR10("./data", train=True, download=True, transform=transforms.ToTensor())
cifar10_test = CIFAR10("./data", train=False, download=True, transform=transforms.ToTensor())

batch_size = 64
train_loader = DataLoader(cifar10_train, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(cifar10_test, batch_size=len(cifar10_test), shuffle=False)

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16*5*5, 256)
        self.fc2 = nn.Linear(256, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16*5*5)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

net = Net()
if torch.cuda.is_available():
    net.cuda()

loss_fnc = nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters())

record_loss_train = []
record_loss_test = []

x_test, t_test = next(iter(test_loader))
if torch.cuda.is_available():
    x_test, t_test = x_test.cuda(), t_test.cuda()

for i in range(10):
    net.train()
    loss_train = 0
    for j, (x, t) in enumerate(train_loader):
        if torch.cuda.is_available():
            x, t = x.cuda(), t.cuda()
        y = net(x)
        loss = loss_fnc(y, t)
        loss_train += loss.item()
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    loss_train /= j+1
    record_loss_train.append(loss_train)

    net.eval()
    y_test = net(x_test)
    loss_test = loss_fnc(y_test, t_test).item()
    record_loss_test.append(loss_test)

100%|██████████| 170M/170M [00:03<00:00, 48.4MB/s]


CPU times: user 1min 23s, sys: 1.62 s, total: 1min 25s
Wall time: 1min 31s


In [4]:
a = 12
b = 34
print(a + b)

46


In [5]:
!pip list

Package                               Version
------------------------------------- -------------------
absl-py                               1.4.0
accelerate                            1.8.1
aiofiles                              24.1.0
aiohappyeyeballs                      2.6.1
aiohttp                               3.11.15
aiosignal                             1.3.2
alabaster                             1.0.0
albucore                              0.0.24
albumentations                        2.0.8
ale-py                                0.11.1
altair                                5.5.0
annotated-types                       0.7.0
antlr4-python3-runtime                4.9.3
anyio                                 4.9.0
argon2-cffi                           25.1.0
argon2-cffi-bindings                  21.2.0
array_record                          0.7.2
arviz                                 0.21.0
astropy                               7.1.0
astropy-iers-data                     0.2025.6.23.0.

In [7]:
import torch

a = torch.tensor([1,2,3])
print(a, type(a))

tensor([1, 2, 3]) <class 'torch.Tensor'>


In [12]:
print("--- 2차원 리스트로부터 생성 ---")
b = torch.tensor([[1, 2],
                  [3, 4]])
print(b)

print("--- dtype을 지정하고, 배정도의 Tensor로 한다 ---")
c = torch.tensor([[1, 2],
                  [3, 4]], dtype=torch.float64)
print(c)

print("--- 0부터 9까지의 수치로 초기화 ---")
d = torch.arange(0, 10)
print(d)

print("--- 모든 값이 0인 2×3의 Tensor ---")
e = torch.zeros(2, 3)
print(e)

print("--- 모든 값이 난수인 2×3의 Tensor ---")
f = torch.rand(2, 3)
print(f)

print("--- Tensor의 형태는 size 메서드로 취득 ---")
print(f.size())

--- 2차원 리스트로부터 생성 ---
tensor([[1, 2],
        [3, 4]])
--- dtype을 지정하고, 배정도의 Tensor로 한다 ---
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
--- 0부터 9까지의 수치로 초기화 ---
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
--- 모든 값이 0인 2×3의 Tensor ---
tensor([[0., 0., 0.],
        [0., 0., 0.]])
--- 모든 값이 난수인 2×3의 Tensor ---
tensor([[0.5011, 0.8859, 0.4487],
        [0.0759, 0.1963, 0.7636]])
--- Tensor의 형태는 size 메서드로 취득 ---
torch.Size([2, 3])


In [13]:
print("--- -5부터 5까지의 연속값을 10 생성 ---")
g = torch.linspace(-5, 5, 10)
print(g)

--- -5부터 5까지의 연속값을 10 생성 ---
tensor([-5.0000, -3.8889, -2.7778, -1.6667, -0.5556,  0.5556,  1.6667,  2.7778,
         3.8889,  5.0000])


In [15]:

print("--- Tensor → NumPy ---")
a = torch.tensor([[1, 2],
                  [3, 4.]])
b = a.numpy()
print(b)

print("--- NumPy → Tensor ---")
c = torch.from_numpy(b)
print(c)

--- Tensor → NumPy ---
[[1. 2.]
 [3. 4.]]
--- NumPy → Tensor ---
tensor([[1., 2.],
        [3., 4.]])


In [16]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print("--- 2개의 인덱스를 지정 ---")
print(a[0, 1])

print("--- 범위를 지정 ---")
print(a[1:2, :2])

print("--- 리스트로 여러 개의 인덱스를 지정 ---")
print(a[:, [0, 2]])

print("--- 3보다 큰 요소만을 지정 ---")
print(a[a>3])

print("--- 요소의 변경 ---")
a[0, 2] = 11
print(a)

print("--- 요소의 일괄 변경 ---")
a[:, 1] = 22
print(a)

print("--- 10보다 큰 요소만 변경 ---")
a[a>10] = 33
print(a)

--- 2개의 인덱스를 지정 ---
tensor(2)
--- 범위를 지정 ---
tensor([[4, 5]])
--- 리스트로 여러 개의 인덱스를 지정 ---
tensor([[1, 3],
        [4, 6]])
--- 3보다 큰 요소만을 지정 ---
tensor([4, 5, 6])
--- 요소의 변경 ---
tensor([[ 1,  2, 11],
        [ 4,  5,  6]])
--- 요소의 일괄 변경 ---
tensor([[ 1, 22, 11],
        [ 4, 22,  6]])
--- 10보다 큰 요소만 변경 ---
tensor([[ 1, 33, 33],
        [ 4, 33,  6]])


In [19]:
# 벡터
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# 행렬
c = torch.tensor([[6, 5, 4],
                  [3, 2, 1]])

print("--- 벡터와 스칼라의 연산 ---")
print(a + 3)

print("--- 벡터끼리의 연산 ---")
print(a + b)

print("--- 행렬과 스칼라의 연산 ---")
print(c + 2)

print("--- 행렬과 백터의 연산(브로드 캐스트) ---")
print(c + a)

print("--- 행렬끼리의 연산 ---")
print(c + c)

--- 벡터와 스칼라의 연산 ---
tensor([4, 5, 6])
--- 벡터끼리의 연산 ---
tensor([5, 7, 9])
--- 행렬과 스칼라의 연산 ---
tensor([[8, 7, 6],
        [5, 4, 3]])
--- 행렬과 백터의 연산(브로드 캐스트) ---
tensor([[7, 7, 7],
        [4, 4, 4]])
--- 행렬끼리의 연산 ---
tensor([[12, 10,  8],
        [ 6,  4,  2]])


In [21]:
a = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7])  # 1차원 Tensor
b = a.view(2, 4)  # (2, 4)의 2차원 Tensor로 변환
print(b)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


In [24]:
c = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7])  # 1차원 Tensor
d = c.view(2, -1)  # (2, 4)의 2차원 Tensor로 변환
print(d)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


In [28]:
e = torch.tensor([[[0, 1],
                   [2, 3]],
                  [[4, 5],
                   [6, 7]]])  # 3차원 Tensor
f = c.view(-1)  # 1차원 Tensor로 변환
print(f)

tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [29]:
#%%
print("--- 요소 수가 1인 차원이 포함되는 4차원 Tensor ---")
g = torch.arange(0, 8).view(1, 2, 1, 4)
print(g)

print("--- 요소 수가 1인 차원을 삭제 ---")
h = g.squeeze()
print(h)

--- 요소 수가 1인 차원이 포함되는 4차원 Tensor ---
tensor([[[[0, 1, 2, 3]],

         [[4, 5, 6, 7]]]])
--- 요소 수가 1인 차원을 삭제 ---
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


In [30]:
print("--- 2차원 Tensor ---")
i = torch.arange(0, 8).view(2, -1)
print(i)

print("--- 요소 수가 1인 차원을 가장 안쪽 (2)에 추가 ---")
j = i.unsqueeze(2)
print(j)

--- 2차원 Tensor ---
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
--- 요소 수가 1인 차원을 가장 안쪽 (2)에 추가 ---
tensor([[[0],
         [1],
         [2],
         [3]],

        [[4],
         [5],
         [6],
         [7]]])


In [31]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6.]])

print("--- 평균값을 구하는 함수 ---")
m = torch.mean(a)
print(m.item())  # item()로 값을 꺼낸다

print("--- 평균값을 구하는 메서드 ---")
m = a.mean()
print(m.item())

print("--- 열별 평균값 ---")
print(a.mean(0))

print("--- 합계값 ---")
print(torch.sum(a).item())

print("--- 최댓값 ---")
print(torch.max(a).item())

print("--- 최솟값 ---")
print(torch.min(a).item())

--- 평균값을 구하는 함수 ---
3.5
--- 평균값을 구하는 메서드 ---
3.5
--- 열별 평균값 ---
tensor([2.5000, 3.5000, 4.5000])
--- 합계값 ---
21.0
--- 최댓값 ---
6.0
--- 최솟값 ---
1.0


In [32]:
import torch

a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
b = torch.tensor([1, 2, 3])

print("--- 합 ---")
print(a + b)

print("--- 차 ---")
print(a - b)

print("--- 곱 ---")
print(a * b)

print("--- 몫(소수) ---")
print(a / b)

print("--- 몫(정수) ---")
print(a // b)

print("--- 나머지 ---")
print(a % b)

--- 합 ---
tensor([[2, 4, 6],
        [5, 7, 9]])
--- 차 ---
tensor([[0, 0, 0],
        [3, 3, 3]])
--- 곱 ---
tensor([[ 1,  4,  9],
        [ 4, 10, 18]])
--- 몫(소수) ---
tensor([[1.0000, 1.0000, 1.0000],
        [4.0000, 2.5000, 2.0000]])
--- 몫(정수) ---
tensor([[1, 1, 1],
        [4, 2, 2]])
--- 나머지 ---
tensor([[0, 0, 0],
        [0, 1, 0]])
